name: Deploy Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: Deploy Functions
        run: |
          gcloud functions deploy yakutsk-bot \
            --source=./cloud_functions \
            --region=us-central1 \
            --entry-point=post_tweet \
            --runtime=python38 \
            --trigger-http \
            --set-env-vars API_KEY=${{ secrets.API_KEY }} \
            --set-env-vars API_SECRET=${{ secrets.API_SECRET }} \
            --set-env-vars BEARER_TOKEN=${{ secrets.BEARER_TOKEN }} \
            --set-env-vars ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} \
            --set-env-vars ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
            --set-env-vars WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}

