name: Deploy Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    env:
      REGION: us-central1
      ENTRY_POINT: yakutsk-bot
      TOPIC: 
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: Deploy Functions
        run: |
          gcloud functions deploy yakutsk-bot \
            --source ./cloud_functions \
            --region=us-central1 \
            --entry-point post_tweet \ 
            --runtime python38 \
            --trigger-http \

